# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          cat << EOF > .env
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          IMDB_API_KEY=${{ secrets.IMDB_API_KEY }}
          API_KEY=${{ secrets.API_KEY }}
          AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          PROJECT_ID=${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }}
          MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }}
          APP_ID=${{ secrets.APP_ID }}
          EOF
      - name: Build docker and run tests
        run: |
          echo --- Building and starting up docker containers ---
          docker-compose -f docker-compose-ci.yml up
          echo --- Containers up ---
